//
// Created by nils-christian on 25.05.21.
//

#ifndef PIPSIPMPP_PREPROCESSTYPE_H
#define PIPSIPMPP_PREPROCESSTYPE_H

enum class ScalerType { NONE, EQUILIBRIUM, GEOMETRIC_MEAN, GEOMETRIC_MEAN_EQUILIBRIUM, CURTIS_REID };
enum class PresolverType { NONE, PRESOLVE };

#endif //PIPSIPMPP_PREPROCESSTYPE_H
