//
// Created by nils-christian on 25.05.21.
//

#ifndef PIPSIPMPP_INTERIORPOINTMETHODTYPE_HPP
#define PIPSIPMPP_INTERIORPOINTMETHODTYPE_HPP

enum class InteriorPointMethodType { PRIMAL, PRIMAL_DUAL };

#endif //PIPSIPMPP_INTERIORPOINTMETHODTYPE_HPP
