//
// Created by nils-christian on 25.05.21.
//

#ifndef PIPSIPMPP_MEHROTRASTRATEGYTYPE_H
#define PIPSIPMPP_MEHROTRASTRATEGYTYPE_H

enum class MehrotraHeuristic { PRIMAL, PRIMAL_DUAL };

#endif //PIPSIPMPP_MEHROTRASTRATEGYTYPE_H
